{{ config(materialized='iceberg_table') }}

with staging as (

    select
        event_id,
        message_id,
        end_to_end_id,
        transaction_id,
        creation_at,
        number_of_transactions,
        control_sum,
        instructed_amount,
        currency,
        debtor_name,
        creditor_name,
        debtor_agent_bic,
        debtor_agent_name,
        creditor_agent_bic,
        creditor_agent_name,
        debtor_account_id,
        debtor_account_issuer,
        creditor_account_id,
        creditor_account_issuer,
        creditor_account_scheme,
        remittance_information,
        initiating_party_name,
        initiating_party_id,
        initiating_party_id_issuer,
        clearing_system_reference,
        uetr,
        equivalent_amount,
        equivalent_amount_currency,
        countervalue_amount,
        countervalue_amount_currency,
        charge_amount,
        charge_amount_currency,
        charge_bearer,
        purpose_code,
        purpose_proprietary,
        ultimate_debtor_name,
        ultimate_creditor_name,
        related_creditor_name,
        creditor_reference_information,
        referred_document_type,
        referred_document_number,
        referred_document_date,
        regulatory_report_type,
        regulatory_report_id,
        regulatory_report_date,
        regulatory_report_amount,
        regulatory_report_currency,
        supplementary_data_id,
        supplementary_data,
        debtor_address_lines,
        debtor_town_name,
        debtor_country_subdivision,
        debtor_country,
        debtor_postal_code,
        creditor_address_lines,
        creditor_town_name,
        creditor_country_subdivision,
        creditor_country,
        creditor_postal_code,
        debtor_agent_address_lines,
        debtor_agent_town_name,
        debtor_agent_country_subdivision,
        debtor_agent_country,
        debtor_agent_postal_code,
        creditor_agent_address_lines,
        creditor_agent_town_name,
        creditor_agent_country_subdivision,
        creditor_agent_country,
        creditor_agent_postal_code,
        mobile_network,
        kafka_topic,
        kafka_partition,
        kafka_offset,
        kafka_timestamp,
        category,
        source_system,
        source_group,
        year,
        month,
        day,
        load_timestamp,
        record_source
    from {{ ref('stg_pdm_mobile_mtn_pacs008') }}

)

select *
from staging
