{
  "type": "record", "name": "TechnicalPaymentEvent", "namespace": "com.payments.platform",
  "fields": [
    {"name":"event_id","type":"string"}, {"name":"message_id","type":"string"},
    {"name":"event_family","type":"string","default":"TECHNICAL_PAYMENT_EVENT"}, {"name":"event_type","type":"string"},
    {"name":"correlation_id","type":"string"}, {"name":"instruction_id","type":["null","string"],"default":null},
    {"name":"end_to_end_id","type":"string"}, {"name":"transaction_id","type":["null","string"],"default":null},
    {"name":"uetr","type":["null","string"],"default":null}, {"name":"business_reference","type":"string"},
    {"name":"x_trace","type":"string"}, {"name":"x_channel","type":"string"},
    {"name":"x_beneficiary_sa","type":["null","string"],"default":null}, {"name":"x_source_system","type":"string"},
    {"name":"x_target_system","type":"string"}, {"name":"x_service","type":"string"},
    {"name":"x_operation","type":"string"}, {"name":"x_component","type":"string"},
    {"name":"x_node","type":"string"}, {"name":"x_host","type":"string"},
    {"name":"x_payment_route","type":["null","string"],"default":null},
    {"name":"x_originating_institution","type":["null","string"],"default":null},
    {"name":"x_intermediary_institution","type":["null","string"],"default":null},
    {"name":"x_route_decision","type":["null","string"],"default":null},
    {"name":"x_validation_status","type":["null","string"],"default":null},
    {"name":"x_submission_status","type":["null","string"],"default":null},
    {"name":"x_provider","type":["null","string"],"default":null},
    {"name":"x_network","type":["null","string"],"default":null},
    {"name":"x_wallet_reference","type":["null","string"],"default":null},
    {"name":"x_provider_transaction_id","type":["null","string"],"default":null},
    {"name":"x_credit_status","type":["null","string"],"default":null},
    {"name":"x_agent_reference","type":["null","string"],"default":null},
    {"name":"x_cashout_status","type":["null","string"],"default":null},
    {"name":"technical_stage","type":"string"}, {"name":"technical_status","type":"string"},
    {"name":"event_timestamp","type":"string"}, {"name":"processing_timestamp","type":"string"},
    {"name":"x_latency_ms","type":"long"}, {"name":"x_retry_count","type":"int"},
    {"name":"x_timeout_indicator","type":"boolean"}, {"name":"x_error_code","type":["null","string"],"default":null},
    {"name":"x_error_category","type":["null","string"],"default":null},
    {"name":"x_attributes","type":["null",{"type":"map","values":"string"}],"default":null},
    {"name":"schema_version","type":"string","default":"2.0.0"}
  ]
}
