FROM python:3.11-slim

WORKDIR /app
COPY services/kafka-consumer-events/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY services/kafka-consumer-events/kafka_consumer_events.py /app/consumer.py
COPY services/kafka-consumer-events/raw_data_healthcheck.py /app/raw_data_healthcheck.py
COPY services/kafka-consumer-events/replay_dlq.py /app/replay_dlq.py

ENV PYTHONUNBUFFERED=1

ENTRYPOINT ["python3", "/app/consumer.py"]
