FROM trinodb/trino:latest

# Copy custom configurations
COPY platform/trino/etc /etc/trino/
COPY platform/trino/catalog /etc/trino/catalog/

EXPOSE 8080

USER trino
CMD ["/usr/lib/trino/bin/run-trino"]
