FROM trinodb/trino:latest

# Copy custom configurations
COPY platform/trino/etc /usr/lib/trino/etc/
COPY platform/trino/catalog /usr/lib/trino/etc/catalog/

EXPOSE 8080

USER trino
CMD ["/usr/lib/trino/bin/run-trino"]
