FROM python:3.11-slim

# Copy requirements and install
COPY services/payments-api/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

WORKDIR /app/src

ENV API_PORT=7001

ENTRYPOINT ["python3", "-m", "api.py"]
