FROM postgres:15-alpine

# Copy healthcheck script
COPY platform/postgres/healthchecks/healthcheck.sh /healthcheck.sh
RUN chmod +x /healthcheck.sh

# Install dependencies
RUN apk add --no-cache curl

HEALTHCHECK --interval=5s --timeout=5s --retries=20 \
  CMD pg_isready -U ${POSTGRES_USER} || exit 1

CMD ["/healthcheck.sh"]
