FROM confluentinc/cp-kafka:latest

# Copy init script
COPY platform/kafka/create-topics.sh /app/create-topics.sh
COPY platform/kafka/topics.yaml /app/topics.yaml
RUN chmod +x /app/create-topics.sh

# Install python for yaml parsing
RUN apt-get update && apt-get install -y python3 python3-yaml && rm -rf /var/lib/apt/lists/*

CMD ["/app/create-topics.sh"]
