FROM confluentinc/cp-kafka:7.5.0

USER root

RUN yum install -y jq curl \
    && yum clean all

COPY platform/kafka/create-topics.sh /app/create-topics.sh
COPY platform/kafka/topics.yaml /app/topics.yaml

RUN chmod +x /app/create-topics.sh

ENTRYPOINT ["/app/create-topics.sh"]