ARG TRINO_BASE_IMAGE
FROM ${TRINO_BASE_IMAGE}

# Copy custom configurations
COPY platform/trino/etc /etc/trino/
COPY platform/trino/catalog /etc/trino/catalog/

EXPOSE 8080

USER trino
CMD ["/usr/lib/trino/bin/run-trino"]
