connector.name=postgresql
connection-url=jdbc:postgresql://${ENV:POSTGRES_HOST}:${ENV:POSTGRES_PORT}/${ENV:TRINO_DATABASE_NAME}
connection-user=${env:POSTGRES_USER}
connection-password=${env:POSTGRES_PASSWORD}
