# /home/hochom/projects/dp-pdm-ai-platform/transform/dbt/dbt_project.yml

name: "pdm_platform"
version: "1.0.0"
config-version: 2

profile: "pdm_platform"

# ------------------------------------------------------------------------------
# Project paths
# ------------------------------------------------------------------------------

model-paths:
  - "models"

analysis-paths:
  - "analyses"

test-paths:
  - "tests"

seed-paths:
  - "seeds"

macro-paths:
  - "macros"

snapshot-paths:
  - "snapshots"

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

# ------------------------------------------------------------------------------
# Model configuration
# ------------------------------------------------------------------------------

models:
  pdm_platform:
    +materialized: table

    staging:
      +database: "{{ env_var('DBT_STAGING_DATABASE') }}"
      +materialized: view
      +schema: staging

    bronze:
      +database: "{{ env_var('DBT_BRONZE_DATABASE') }}"
      +materialized: table
      +schema: bronze

    silver:
      +database: "{{ env_var('DBT_SILVER_DATABASE') }}"
      +materialized: table
      +schema: silver

    gold:
      +database: "{{ env_var('DBT_GOLD_DATABASE') }}"
      +materialized: table
      +schema: gold

    silver_vault:
      +database: "{{ env_var('DBT_SILVER_VAULT_DATABASE') }}"
      +materialized: table
      +schema: silver_vault

    consumption:
      +database: "{{ env_var('DBT_CONSUMPTION_DATABASE') }}"
      +materialized: table
      +schema: consumption

# ------------------------------------------------------------------------------
# Project variables
# ------------------------------------------------------------------------------

vars:
  s3_bucket: "{{ env_var('OBJECT_STORE_BUCKET') }}"
  s3_path: "{{ env_var('RAW_ROOT') }}"
  iceberg_catalog: "{{ env_var('ICEBERG_CATALOG') }}"
