# /home/hochom/projects/dp-ai-payments-platform/transform/dbt/dbt_project.yml
name: 'pdm_platform'
version: '1.0.0'
config-version: 2

profile: 'pdm_platform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  pdm_platform:
    +materialized: table
    staging:
      +materialized: view
      +schema: staging
    bronze:
      +materialized: table
      +schema: bronze
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table
      +schema: gold
    consumption:
      +materialized: table
      +schema: consumption

vars:
  s3_bucket: "dp-ai-payment"
  s3_path: "raw"
  iceberg_catalog: "pdm_catalog"
