version: 2

models:
  - name: br_pdm_cpo_psn_pain002
    description: Source-shaped CPO PSN PAIN.002 records.
  - name: br_pdm_cpo_plm_pain002
    description: Source-shaped CPO PLM PAIN.002 records.
  - name: br_pdm_icmn_pmn_pain001
    description: Source-shaped ICMN PMN PAIN.001 records.
  - name: br_pdm_icmn_vpm_pain001
    description: Source-shaped ICMN VPM PAIN.001 records.
